name: ServiceNow Task on GitHub Push

on:
  push:
    branches: [main]
  workflow_dispatch:
name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check whether secrets exist
        run: |
          if [ -z "${{ secrets.SN_INSTANCE_URL }}" ]; then
            echo "SN_INSTANCE_URL is EMPTY"
          else
            echo "SN_INSTANCE_URL is PRESENT"
          fi

          if [ -z "${{ secrets.SN_USERNAME }}" ]; then
            echo "SN_USERNAME is EMPTY"
          else
            echo "SN_USERNAME is PRESENT"
          fi

          if [ -z "${{ secrets.SN_PASSWORD }}" ]; then
            echo "SN_PASSWORD is EMPTY"
          else
            echo "SN_PASSWORD is PRESENT"
          fi
